

#default API key required to invoke the API, deployments can override to supply a secret value to enhance the security and prevent non-authorized invocations
migratedb:
  apikey: ABC123

server:
  port: 8080
  servlet:
    context-path: /migratedb

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS,Z}Z %-5p [%logger{15}] [%thread] :: %msg %n"
  level:
    root: WARN
    ca:
      uhn:
        fhir: INFO
    com:
      github:
        xcrigx: INFO

spring:
  flyway:
    enabled: false


